# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-15 19:52
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20170515_1120'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment_author', models.CharField(max_length=200)),
                ('comment_text', models.TextField()),
                ('comment_created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('comment_approved', models.BooleanField(default=False)),
                ('comment_post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='blog.Post')),
            ],
            options={
                'db_table': 'comment',
            },
        ),
    ]
