# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-15 20:23
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_comment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='comment_approved',
            new_name='approved_comment',
        ),
        migrations.RenameField(
            model_name='comment',
            old_name='comment_author',
            new_name='author',
        ),
        migrations.RenameField(
            model_name='comment',
            old_name='comment_created_date',
            new_name='created_date',
        ),
        migrations.RenameField(
            model_name='comment',
            old_name='comment_post',
            new_name='post',
        ),
        migrations.RenameField(
            model_name='comment',
            old_name='comment_text',
            new_name='text',
        ),
        migrations.AlterModelTable(
            name='comment',
            table=None,
        ),
    ]
